name: classmate_demo
description: A new Flutter project.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Data Persistence (replaces localStorage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # API Calls (for Chatbot)
  http: ^1.2.1

  # UI & Styling
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.68.0

  # Markdown Rendering (for Chatbot)
  flutter_markdown: ^0.7.1

  # General Utilities
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Required for Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
